### ISSUE TITLE
Problem with running backend server

### ISSUE THREAD

**Issue by pawelbrzoza** [superdurszlak/candidate-match#26]
C:\Users\Paweł\Documents\GitHub\candidate-match\backend>run.py
Traceback (most recent call last):
  File "C:\Users\Paweł\Documents\GitHub\candidate-match\backend\run.py", line 1, in <module>
    from backend.app.flask import flask_app
ModuleNotFoundError: No module named 'backend'

**Comment by superdurszlak** [comment]
Pull latest version from master, there's no module named 'backend' anymore.

**Comment by pawelbrzoza** [comment]
still can't work..

C:\Users\Paweł\Documents\GitHub\candidate-match\backend>run.py
Traceback (most recent call last):
  File "C:\Users\Paweł\Documents\GitHub\candidate-match\backend\run.py", line 1, in <module>
    from app.flask import flask_app
  File "C:\Users\Paweł\Documents\GitHub\candidate-match\backend\app\flask.py", line 13, in <module>
    from flask_wtf.csrf import CSRFProtect
ModuleNotFoundError: No module named 'flask_wtf'

**Comment by superdurszlak** [comment]
Have you installed required modules?
```bash
pip install -r requirements.txt
```

**Comment by pawelbrzoza** [comment]
thanks @superdurszlak that's helped
